name: Run Windows 10 on Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
          docker --version
          docker-compose --version

      - name: Create Windows 10 YAML
        run: |
          cat <<EOF > windows10.yml
          version: "3"
          services:
            windows:
              image: dockurr/windows
              container_name: windows
              environment:
                VERSION: "10"
                USERNAME: "admin"
                PASSWORD: "admin@123"
                RAM_SIZE: "4G"
                CPU_CORES: "4"
                DISK_SIZE: "400G"
                DISK2_SIZE: "100G"
              devices:
                - /dev/kvm
                - /dev/net/tun
              cap_add:
                - NET_ADMIN
              ports:
                - 8006:8006
                - 3389:3389/tcp
                - 3389:3389/udp
              stop_grace_period: 2m
          EOF

      - name: Run Windows 10 Container
        run: |
          sudo systemctl start docker
          sudo docker-compose -f windows10.yml up -d

      - name: Check Running Containers
        run: sudo docker ps -a
